# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - __sitename__

on:
  push:
    branches:
      - __branch__
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    __permissions__
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '__runtimeversion__'

      - name: Install Python dependencies
        run: |
          python -m venv env
          .\\env\\Scripts\\activate
          pip install -r requirements.txt

      - name: Zip the application files
        run: Compress-Archive .\\* app.zip
      __login-to-azure-step__
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: '__sitename__'
          slot-name: '__slotname__'
          package: '.\\app.zip'
          __publishing-profile__