# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
jobs:
  - job: EtwLogger
    steps:
      # - task: UseDotNet@2
      #   displayName: 'Use .NET Core 3.x'
      #   inputs:
      #     packageType: 'sdk'
      #     version: '3.x'
      #     includePreviewVersions: true
      - task: DotNetCoreCLI@2
        displayName: 'Restore EtwLogger'
        inputs:
          command: 'restore'
          feedsToUse: 'select'
          projects: 'EtwLogger/EtwLogger.csproj'
          includeNuGetOrg: true
      - task: DotNetCoreCLI@2
        displayName: 'Build EtwLogger'
        inputs:
          command: 'build'
          arguments: '--configuration Release'
          projects: 'EtwLogger/EtwLogger.csproj'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'EtwLogger/bin/Release/netcoreapp3.1/'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: EtwLogger'
        inputs:
          ArtifactName: EtwLogger

  - job: Server
    pool:
      vmImage: 'macOS-10.14'
    dependsOn:
      - EtwLogger
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download EtwLogger Build Artifacts'
        inputs:
          artifactName: EtwLogger
          downloadPath: $(System.DefaultWorkingDirectory)

      - task: CopyFiles@2
        displayName: 'Copy EtwLogger Build Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/EtwLogger
          TargetFolder: server/dist/EtwLogger

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: server/dist
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/package.zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: dest'
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/package.zip'
          ArtifactName: dest
