# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
jobs:
  - job: Server
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          cd server
          npm ci
        displayName: 'npm install'

      - script: |
          cd server
          npm run build
        displayName: 'Setup Environment Variables and Build Resources'
        env:
          bitbucketClientId: $(bitbucketClientId)
          githubClientId: $(githubClientId)
          githubClientSecret: $(githubClientSecret)
          githubRedirectUrl: $(githubRedirectUrl)
          bitbucketClientSecret: $(bitbucketClientSecret)
          bitbucketRedirectUrl: $(bitbucketRedirectUrl)
          dropboxClientSecret: $(dropboxClientSecret)
          dropboxClientId: $(dropboxClientId)
          dropboxRedirectUrl: $(dropboxRedirectUrl)
          onedriveClientSecret: $(onedriveClientSecret)
          onedriveClientID: $(onedriveClientID)
          onedriveRedirectUrl: $(onedriveRedirectUrl)

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: server/build
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: server'
        inputs:
          ArtifactName: server

  - job: ReactBuild
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          cd client-react
          npm ci
        displayName: 'npm install'

      - script: |
          cd client-react
          export REACT_APP_CACHE_KEY=$(uuidgen)
          npm run build
        displayName: 'build production react'
        env:
          REACT_APP_RUNETIME_TYPE: $(reactRuntimeType)
          REACT_APP_APPLICATION_INSIGHTS_KEY: $(applicationInsightsKey)
          REACT_APP_APPLICATION_VERSION: ${BUILD_BUILDID}

      - script: |
          cd client-react/build
          mv index.html index.react.html
        displayName: 'Rename index.html'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: client-react/build
          TargetFolder: '$(Build.ArtifactStagingDirectory)/public/react'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: react-build'
        inputs:
          ArtifactName: react-build

  - job: AngularFull
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          cd client
          npm ci
        displayName: 'npm install'

      - script: |
          cd client
          node_modules/.bin/ng build --progress false --output-path="public/ng-full"
        displayName: 'ng build full'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: client/public
          TargetFolder: '$(Build.ArtifactStagingDirectory)/public'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: angular-full'
        inputs:
          ArtifactName: angular-full

  - job: AngularMin
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'
        
      - script: |
          npm install -g gulp-cli
        displayName: 'install gulp'

      - script: |
          cd client
          npm ci
        displayName: 'npm install'

      - script: |
          cd client
          node_modules/.bin/ng build --progress false --prod --environment=prod --output-path="../server/public/ng-min"
        displayName: 'ng build full'

      - script: |
          cd server
          npm ci
          gulp replace-tokens-for-minimized-angular
        displayName: 'Generate config file with angular files'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: server/public
          TargetFolder: '$(Build.ArtifactStagingDirectory)/public'

      - task: CopyFiles@2
        displayName: 'Copy Assets to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: client/src/assets
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: angular-min'
        inputs:
          ArtifactName: angular-min

  - job: PublishArtifacts
    pool:
      vmImage: 'macOS-10.13'

    dependsOn:
      - Server
      - AngularFull
      - AngularMin
      - ReactBuild
    steps:
      - checkout: none

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - task: DownloadBuildArtifacts@0
        displayName: 'Download Server Artifacts'
        inputs:
          artifactName: server
          downloadPath: $(System.DefaultWorkingDirectory)

      - task: DownloadBuildArtifacts@0
        displayName: 'Download Angular Full Artifacts'
        inputs:
          artifactName: angular-full
          downloadPath: $(System.DefaultWorkingDirectory)

      - task: DownloadBuildArtifacts@0
        displayName: 'Download Angular Min Artifacts'
        inputs:
          artifactName: angular-min
          downloadPath: $(System.DefaultWorkingDirectory)

      - task: DownloadBuildArtifacts@0
        displayName: 'Download React Build Artifacts'
        inputs:
          artifactName: react-build
          downloadPath: $(System.DefaultWorkingDirectory)

      - task: CopyFiles@2
        displayName: 'Copy Server Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/server
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: CopyFiles@2
        displayName: 'Copy Angular Full Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/angular-full
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: CopyFiles@2
        displayName: 'Copy Angular Min Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/angular-min
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: CopyFiles@2
        displayName: 'Copy React Build Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/react-build
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - script: |
          cd $(Build.ArtifactStagingDirectory)
          npm ci --production
        displayName: 'delete dev node_modules and install prod'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/package.zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: dest'
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/package.zip'
          ArtifactName: dest
