export const Links = {
  applicationSettingsInfo: 'https://go.microsoft.com/fwlink/?linkid=2086665',
  pythonStackInfo: 'https://go.microsoft.com/fwlink/?linkid=852196',
  clientAffinityInfo: 'https://go.microsoft.com/fwlink/?linkid=798249',
  alwaysOnInfo: 'https://go.microsoft.com/fwlink/?linkid=2086196',
  ftpInfo: 'https://go.microsoft.com/fwlink/?linkid=871316',
  funcConnStringsLearnMore: 'https://go.microsoft.com/fwlink/?linkid=875276',
  mountedStorageLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2088516',
  runtimeScaleMonitoringLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2104710',
  remoteDebuggingLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2116583',
  readOnlyPythonAppLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2074230',
  readOnlyVSGeneratedFunctionLearnMore: 'https://go.microsoft.com/fwlink/?linkid=856288',
  staticSiteEnvironmentVariablesLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2128074',
  // TODO (krmitta): Update the learn more link with the correct fwlink
  functionsPrivateLinkLearnMore: 'https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options',
  durableFunctionExtensionLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2133558',
  standaloneCreateLearnMore: 'https://go.microsoft.com/fwlink/?linkid=848756',
  vmSizeLearnMore: 'https://go.microsoft.com/fwlink/?linkid=873022',
  appServicePricing: 'https://go.microsoft.com/fwlink/?linkid=873021',
  extensionInstallHelpLink: 'https://go.microsoft.com/fwlink/?linkid=2010300',
  funcStorageLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2010003',
  updateExtensionsLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2013353',
  deploymentSlotsLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2014035',
  communityTemplatesLink: 'https://go.microsoft.com/fwlink/?linkid=2022552',
  linuxContainersLearnMore: 'https://go.microsoft.com/fwlink/?linkid=861969',
  premiumV2NotAvailableLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2009376',
  azureComputeUnitLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2027465',
  pv2UpsellInfoLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2028474',
  ipRestrictionsLearnMore: 'https://go.microsoft.com/fwlink/?linkid=854597',
  appDensityWarningLink: 'https://go.microsoft.com/fwlink/?linkid=2098431',
  byosBlobReadonlyLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2110146',
  extensionBundlesRequiredLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2116575',
  cronLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2117147&clcid=0x409',
  quickstartViewDocumentation: 'https://go.microsoft.com/fwlink/?linkid=2119201',
  bindingDirectionLearnMore: 'https://go.microsoft.com/fwlink/?linkid=2121806&clcid=0x409',
};

export const DeploymentCenterLinks = {
  appServiceDocumentation: 'https://go.microsoft.com/fwlink/?linkid=874656',
  configureDeployment: 'https://go.microsoft.com/fwlink/?linkid=2086046',
  containerContinuousDeploy: 'https://go.microsoft.com/fwlink/?linkid=2133570',
};
