//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureFunctions.ResourcesPortal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureFunctions.ResourcesPortal.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string _name {
            get {
                return ResourceManager.GetString("_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string appFunctionSettings_AdvancedSettings {
            get {
                return ResourceManager.GetString("appFunctionSettings_AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow clients to more easily consume your HTTP-triggered functions..
        /// </summary>
        internal static string appFunctionSettings_allowClients {
            get {
                return ResourceManager.GetString("appFunctionSettings_allowClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow your HTTP-triggered functions to be called from within a web browser..
        /// </summary>
        internal static string appFunctionSettings_allowYour {
            get {
                return ResourceManager.GetString("appFunctionSettings_allowYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API definition.
        /// </summary>
        internal static string appFunctionSettings_apiDefiition {
            get {
                return ResourceManager.GetString("appFunctionSettings_apiDefiition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication/Authorization.
        /// </summary>
        internal static string appFunctionSettings_auth {
            get {
                return ResourceManager.GetString("appFunctionSettings_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Integration.
        /// </summary>
        internal static string appFunctionSettings_CI {
            get {
                return ResourceManager.GetString("appFunctionSettings_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Authentication.
        /// </summary>
        internal static string appFunctionSettings_configAuth {
            get {
                return ResourceManager.GetString("appFunctionSettings_configAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure API metadata.
        /// </summary>
        internal static string appFunctionSettings_configureAPI {
            get {
                return ResourceManager.GetString("appFunctionSettings_configureAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Continuous Integration.
        /// </summary>
        internal static string appFunctionSettings_configureCI {
            get {
                return ResourceManager.GetString("appFunctionSettings_configureCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure CORS.
        /// </summary>
        internal static string appFunctionSettings_configureCors {
            get {
                return ResourceManager.GetString("appFunctionSettings_configureCors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy your function code from GitHub, Visual Studio Team Services, and more..
        /// </summary>
        internal static string appFunctionSettings_deploy {
            get {
                return ResourceManager.GetString("appFunctionSettings_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For functions that use the HTTP trigger, you can require calls to be authenticated..
        /// </summary>
        internal static string appFunctionSettings_forFunc {
            get {
                return ResourceManager.GetString("appFunctionSettings_forFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function App Settings.
        /// </summary>
        internal static string appFunctionSettings_functionAppSettings {
            get {
                return ResourceManager.GetString("appFunctionSettings_functionAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your runtime version.
        /// </summary>
        internal static string appFunctionSettings_functionAppSettings1 {
            get {
                return ResourceManager.GetString("appFunctionSettings_functionAppSettings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your runtime version is to upto-date.
        /// </summary>
        internal static string appFunctionSettings_functionAppSettings2 {
            get {
                return ResourceManager.GetString("appFunctionSettings_functionAppSettings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to App Service Settings.
        /// </summary>
        internal static string appFunctionSettings_goToAppSettings {
            get {
                return ResourceManager.GetString("appFunctionSettings_goToAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your function app like any other App Service instance..
        /// </summary>
        internal static string appFunctionSettings_manageFunction {
            get {
                return ResourceManager.GetString("appFunctionSettings_manageFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Size.
        /// </summary>
        internal static string appFunctionSettings_memory {
            get {
                return ResourceManager.GetString("appFunctionSettings_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime version: Latest ({{latestExtensionVersion}}).
        /// </summary>
        internal static string appFunctionSettings_runtimeVersion1 {
            get {
                return ResourceManager.GetString("appFunctionSettings_runtimeVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime version: {{extensionVersion}}. A newer version is available ({{latestExtensionVersion}})..
        /// </summary>
        internal static string appFunctionSettings_runtimeVersion2 {
            get {
                return ResourceManager.GetString("appFunctionSettings_runtimeVersion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App executions.
        /// </summary>
        internal static string appMonitoring_appExecutions {
            get {
                return ResourceManager.GetString("appMonitoring_appExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Usage(Gb Sec).
        /// </summary>
        internal static string appMonitoring_appUsage {
            get {
                return ResourceManager.GetString("appMonitoring_appUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function App Usage.
        /// </summary>
        internal static string appMonitoring_functionAppUsage {
            get {
                return ResourceManager.GetString("appMonitoring_functionAppUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Data.
        /// </summary>
        internal static string appMonitoring_noData {
            get {
                return ResourceManager.GetString("appMonitoring_noData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of executions.
        /// </summary>
        internal static string appMonitoring_ofExecutions {
            get {
                return ResourceManager.GetString("appMonitoring_ofExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Functions.
        /// </summary>
        internal static string azureFunctions {
            get {
                return ResourceManager.GetString("azureFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new functoin triggered by this output.
        /// </summary>
        internal static string binding_createNewFunction {
            get {
                return ResourceManager.GetString("binding_createNewFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string binding_delete {
            get {
                return ResourceManager.GetString("binding_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string binding_documentation {
            get {
                return ResourceManager.GetString("binding_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string binding_go {
            get {
                return ResourceManager.GetString("binding_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name.
        /// </summary>
        internal static string binding_parameterName {
            get {
                return ResourceManager.GetString("binding_parameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        internal static string bindingInput_new {
            get {
                return ResourceManager.GetString("bindingInput_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        internal static string bindingInput_select {
            get {
                return ResourceManager.GetString("bindingInput_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;direction&apos; is missed..
        /// </summary>
        internal static string bindingsValidationDirectionMissed {
            get {
                return ResourceManager.GetString("bindingsValidationDirectionMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown direction: &apos;{{direction}}&apos;..
        /// </summary>
        internal static string bindingsValidationDirectionUnknown {
            get {
                return ResourceManager.GetString("bindingsValidationDirectionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name must be unique in a function: &apos;{{functionName}}&apos;.
        /// </summary>
        internal static string bindingsValidationNameDublicate {
            get {
                return ResourceManager.GetString("bindingsValidationNameDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;name&apos; is missed..
        /// </summary>
        internal static string bindingsValidationNameMissed {
            get {
                return ResourceManager.GetString("bindingsValidationNameMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;type&apos; is missed..
        /// </summary>
        internal static string bindingsValidationTypeMIssed {
            get {
                return ResourceManager.GetString("bindingsValidationTypeMIssed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type: &apos;{{type}}&apos;..
        /// </summary>
        internal static string bindingsValidationTypeUnknown {
            get {
                return ResourceManager.GetString("bindingsValidationTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string configure {
            get {
                return ResourceManager.GetString("configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORS.
        /// </summary>
        internal static string cors {
            get {
                return ResourceManager.GetString("cors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you don&apos;t have a functions container. Select a subscription to create one:.
        /// </summary>
        internal static string dashboard_noFunctionContainer {
            get {
                return ResourceManager.GetString("dashboard_noFunctionContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial has expired.
        /// </summary>
        internal static string dashboard_yourTrialExpiered {
            get {
                return ResourceManager.GetString("dashboard_yourTrialExpiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string errorList_here {
            get {
                return ResourceManager.GetString("errorList_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may be experiencing an error. If you&apos;re having issues, please post them.
        /// </summary>
        internal static string errorList_youMay {
            get {
                return ResourceManager.GetString("errorList_youMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing config: {{error}}.
        /// </summary>
        internal static string errorParsingConfig {
            get {
                return ResourceManager.GetString("errorParsingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string features {
            get {
                return ResourceManager.GetString("features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string filedRequired {
            get {
                return ResourceManager.GetString("filedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Function Error: {{error}}.
        /// </summary>
        internal static string functionCreateErrorDetails {
            get {
                return ResourceManager.GetString("functionCreateErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function creation error! Please try again..
        /// </summary>
        internal static string functionCreateErrorMessage {
            get {
                return ResourceManager.GetString("functionCreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string functionDev_code {
            get {
                return ResourceManager.GetString("functionDev_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Error: {{error}}.
        /// </summary>
        internal static string functionDev_functionErrorDetails {
            get {
                return ResourceManager.GetString("functionDev_functionErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function (${{name}}) Error: {{error}}.
        /// </summary>
        internal static string functionDev_functionErrorMessage {
            get {
                return ResourceManager.GetString("functionDev_functionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Url:.
        /// </summary>
        internal static string functionDev_functionUrl {
            get {
                return ResourceManager.GetString("functionDev_functionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Secret:.
        /// </summary>
        internal static string functionDev_githubSelect {
            get {
                return ResourceManager.GetString("functionDev_githubSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide files.
        /// </summary>
        internal static string functionDev_hideFiles {
            get {
                return ResourceManager.GetString("functionDev_hideFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Error: {{error}}.
        /// </summary>
        internal static string functionDev_hostErrorMessage {
            get {
                return ResourceManager.GetString("functionDev_hostErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string functionDev_Output {
            get {
                return ResourceManager.GetString("functionDev_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request body.
        /// </summary>
        internal static string functionDev_requestBody {
            get {
                return ResourceManager.GetString("functionDev_requestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string functionDev_run {
            get {
                return ResourceManager.GetString("functionDev_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and run.
        /// </summary>
        internal static string functionDev_saveAndRun {
            get {
                return ResourceManager.GetString("functionDev_saveAndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string functionDev_status {
            get {
                return ResourceManager.GetString("functionDev_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View files.
        /// </summary>
        internal static string functionDev_viewFiles {
            get {
                return ResourceManager.GetString("functionDev_viewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only - because you have started editing with source control, this view is read only. You can edit these settings in function.json.
        /// </summary>
        internal static string functionEdit_readOnly {
            get {
                return ResourceManager.GetString("functionEdit_readOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced editor.
        /// </summary>
        internal static string functionIntegrate_advancedEditor {
            get {
                return ResourceManager.GetString("functionIntegrate_advancedEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made will be lost. Are you sure you want to continue?.
        /// </summary>
        internal static string functionIntegrate_changesLost1 {
            get {
                return ResourceManager.GetString("functionIntegrate_changesLost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made to function {{name}} will be lost. Are you sure you want to continue?.
        /// </summary>
        internal static string functionIntegrate_changesLost2 {
            get {
                return ResourceManager.GetString("functionIntegrate_changesLost2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting name:.
        /// </summary>
        internal static string functionIntegrate_settingName {
            get {
                return ResourceManager.GetString("functionIntegrate_settingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard editor.
        /// </summary>
        internal static string functionIntegrate_standardEditor {
            get {
                return ResourceManager.GetString("functionIntegrate_standardEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Function {{name}}?.
        /// </summary>
        internal static string functionManage_areYouSure {
            get {
                return ResourceManager.GetString("functionManage_areYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a template.
        /// </summary>
        internal static string functionNew_chooseTemplate {
            get {
                return ResourceManager.GetString("functionNew_chooseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template is experimental and does not yet have full support. If you run into issues, please file a bug on our &lt;a href=&quot;https://github.com/Azure/azure-webjobs-sdk-templates/issues&quot; target=&quot;_blank&quot;&gt;GitHub repository.&lt;/a&gt;.
        /// </summary>
        internal static string functionNew_experimentalTemplate {
            get {
                return ResourceManager.GetString("functionNew_experimentalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function name.
        /// </summary>
        internal static string functionNew_functionName {
            get {
                return ResourceManager.GetString("functionNew_functionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A function name is required.
        /// </summary>
        internal static string functionNew_functionNameRequired {
            get {
                return ResourceManager.GetString("functionNew_functionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name your function.
        /// </summary>
        internal static string functionNew_nameYourFunction {
            get {
                return ResourceManager.GetString("functionNew_nameYourFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is enabled for the function app. Disable authentication before running the function..
        /// </summary>
        internal static string functionService_authIsEnabled {
            get {
                return ResourceManager.GetString("functionService_authIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error running function ({{name}}). Check logs output for the full error..
        /// </summary>
        internal static string functionService_errorRunningFunc {
            get {
                return ResourceManager.GetString("functionService_errorRunningFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create + get started.
        /// </summary>
        internal static string gettingStarted_createGetStarted {
            get {
                return ResourceManager.GetString("gettingStarted_createGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Apps.
        /// </summary>
        internal static string gettingStarted_functionApps {
            get {
                return ResourceManager.GetString("gettingStarted_functionApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with Azure Functions.
        /// </summary>
        internal static string gettingStarted_getStarted {
            get {
                return ResourceManager.GetString("gettingStarted_getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New function app.
        /// </summary>
        internal static string gettingStarted_newFunctionApp {
            get {
                return ResourceManager.GetString("gettingStarted_newFunctionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription contains no function apps. These are containers where your functions are executed. Create one now..
        /// </summary>
        internal static string gettingStarted_noFunApps {
            get {
                return ResourceManager.GetString("gettingStarted_noFunApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a function app from &lt;a href=&quot;https://portal.azure.com/#create/Microsoft.FunctionApp&quot;&gt;Azure Portal&lt;/a&gt;..
        /// </summary>
        internal static string gettingStarted_orCreate {
            get {
                return ResourceManager.GetString("gettingStarted_orCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        internal static string gettingStarted_selectLocation {
            get {
                return ResourceManager.GetString("gettingStarted_selectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subscription.
        /// </summary>
        internal static string gettingStarted_selectSubscription {
            get {
                return ResourceManager.GetString("gettingStarted_selectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription {{displayName}} ({{ subscriptionId }}) is not white listed for running functions.
        /// </summary>
        internal static string gettingStarted_subIsNotWhitelisted {
            get {
                return ResourceManager.GetString("gettingStarted_subIsNotWhitelisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subscription contains one or more function apps. These are containers where your functions are executed. Select one or create a new one below..
        /// </summary>
        internal static string gettingStarted_thisSub {
            get {
                return ResourceManager.GetString("gettingStarted_thisSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be at least 2 characters.
        /// </summary>
        internal static string gettingStarted_validateContainer1 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be at most 60 characters.
        /// </summary>
        internal static string gettingStarted_validateContainer2 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain letters, numbers, and hyphens (but the first and last character must be a letter or number).
        /// </summary>
        internal static string gettingStarted_validateContainer3 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function app name {{funcName}} isn&apos;t available.
        /// </summary>
        internal static string gettingStarted_validateContainer4 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need an Azure subscription in order to use this service. &lt;a href=&quot;https://azure.microsoft.com/en-us/free/&quot;&gt;Click here&lt;/a&gt; to create a free trial subscription.
        /// </summary>
        internal static string gettingStarted_youNeed {
            get {
                return ResourceManager.GetString("gettingStarted_youNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your function apps.
        /// </summary>
        internal static string gettingStarted_yourFunctionApps {
            get {
                return ResourceManager.GetString("gettingStarted_yourFunctionApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription.
        /// </summary>
        internal static string gettingStarted_yourSubscription {
            get {
                return ResourceManager.GetString("gettingStarted_yourSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        internal static string integrate_inputsHelp {
            get {
                return ResourceManager.GetString("integrate_inputsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        internal static string integrate_outputsHelp {
            get {
                return ResourceManager.GetString("integrate_outputsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigegers.
        /// </summary>
        internal static string integrate_triggersHelp {
            get {
                return ResourceManager.GetString("integrate_triggersHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Choose a language:.
        /// </summary>
        internal static string intro_chooseLanguage {
            get {
                return ResourceManager.GetString("intro_chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Choose a scenario:.
        /// </summary>
        internal static string intro_chooseScenario {
            get {
                return ResourceManager.GetString("intro_chooseScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create this function.
        /// </summary>
        internal static string intro_createThisFunction {
            get {
                return ResourceManager.GetString("intro_createThisFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create your own custom function.
        /// </summary>
        internal static string intro_createYourOwn {
            get {
                return ResourceManager.GetString("intro_createYourOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing.
        /// </summary>
        internal static string intro_dataProcessing {
            get {
                return ResourceManager.GetString("intro_dataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The faster way to functions.
        /// </summary>
        internal static string intro_fasterWay {
            get {
                return ResourceManager.GetString("intro_fasterWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started quickly with a premade function.
        /// </summary>
        internal static string intro_getStarted {
            get {
                return ResourceManager.GetString("intro_getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or get started on your own.
        /// </summary>
        internal static string intro_getStartedOn {
            get {
                return ResourceManager.GetString("intro_getStartedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d prefer another supported language, choose &quot;Create a function from scratch&quot;..
        /// </summary>
        internal static string intro_ifYou {
            get {
                return ResourceManager.GetString("intro_ifYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start from source control..
        /// </summary>
        internal static string intro_startSC {
            get {
                return ResourceManager.GetString("intro_startSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string intro_timer {
            get {
                return ResourceManager.GetString("intro_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook + API.
        /// </summary>
        internal static string intro_webHook {
            get {
                return ResourceManager.GetString("intro_webHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write any function in minutes - whether to run a simple job that cleans up a database or to build a more complex architecture. Creating functions is easier than ever before, whatever your chosen OS, platform, or development method. No install required..
        /// </summary>
        internal static string intro_writeAny {
            get {
                return ResourceManager.GetString("intro_writeAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string logStreaming_clear {
            get {
                return ResourceManager.GetString("logStreaming_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        internal static string logStreaming_copied {
            get {
                return ResourceManager.GetString("logStreaming_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Logs.
        /// </summary>
        internal static string logStreaming_copyLogs {
            get {
                return ResourceManager.GetString("logStreaming_copyLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string logStreaming_logs {
            get {
                return ResourceManager.GetString("logStreaming_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string logStreaming_pause {
            get {
                return ResourceManager.GetString("logStreaming_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string logStreaming_start {
            get {
                return ResourceManager.GetString("logStreaming_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many logs. Refresh rate: {{seconds}} seconds..
        /// </summary>
        internal static string logStreaming_tooManyLogs {
            get {
                return ResourceManager.GetString("logStreaming_tooManyLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Input.
        /// </summary>
        internal static string newInput {
            get {
                return ResourceManager.GetString("newInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Output.
        /// </summary>
        internal static string newOutput {
            get {
                return ResourceManager.GetString("newOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trigger.
        /// </summary>
        internal static string newTrigger {
            get {
                return ResourceManager.GetString("newTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid value.
        /// </summary>
        internal static string notValidValue {
            get {
                return ResourceManager.GetString("notValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        internal static string output {
            get {
                return ResourceManager.GetString("output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only - because you have started editing with source control, this view is read only..
        /// </summary>
        internal static string readOnly {
            get {
                return ResourceManager.GetString("readOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the resource.
        /// </summary>
        internal static string resourceSelect {
            get {
                return ResourceManager.GetString("resourceSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made to function {{name}} will be lost. Are you sure you want to continue?.
        /// </summary>
        internal static string sideBar_changeMade {
            get {
                return ResourceManager.GetString("sideBar_changeMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Function.
        /// </summary>
        internal static string sideBar_newFunction {
            get {
                return ResourceManager.GetString("sideBar_newFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string sideBar_refresh {
            get {
                return ResourceManager.GetString("sideBar_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search my functions.
        /// </summary>
        internal static string sideBar_searchMyFunction {
            get {
                return ResourceManager.GetString("sideBar_searchMyFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop.
        /// </summary>
        internal static string tabNames_develop {
            get {
                return ResourceManager.GetString("tabNames_develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate.
        /// </summary>
        internal static string tabNames_integrate {
            get {
                return ResourceManager.GetString("tabNames_integrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string tabNames_manage {
            get {
                return ResourceManager.GetString("tabNames_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string tabNames_monitor {
            get {
                return ResourceManager.GetString("tabNames_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an input binding.
        /// </summary>
        internal static string templatePicker_chooseInput {
            get {
                return ResourceManager.GetString("templatePicker_chooseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an output binding.
        /// </summary>
        internal static string templatePicker_chooseOutput {
            get {
                return ResourceManager.GetString("templatePicker_chooseOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a template.
        /// </summary>
        internal static string templatePicker_chooseTemplate {
            get {
                return ResourceManager.GetString("templatePicker_chooseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a trigger.
        /// </summary>
        internal static string templatePicker_chooseTrigger {
            get {
                return ResourceManager.GetString("templatePicker_chooseTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string templatePicker_language {
            get {
                return ResourceManager.GetString("templatePicker_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario:.
        /// </summary>
        internal static string templatePicker_scenario {
            get {
                return ResourceManager.GetString("templatePicker_scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made to the current function will be lost. Are you sure you want to continue?.
        /// </summary>
        internal static string topBar_changeMade {
            get {
                return ResourceManager.GetString("topBar_changeMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function app settings.
        /// </summary>
        internal static string topBar_functionAppSettings {
            get {
                return ResourceManager.GetString("topBar_functionAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Azure Functions is available.Visit Function App Settings to upgrade..
        /// </summary>
        internal static string topBar_newVersion {
            get {
                return ResourceManager.GetString("topBar_newVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickstart.
        /// </summary>
        internal static string topBar_quickStart {
            get {
                return ResourceManager.GetString("topBar_quickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string topBar_usage {
            get {
                return ResourceManager.GetString("topBar_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve enjoyed hosting your functions !.
        /// </summary>
        internal static string trialExpired_enjoyedHostingFunctions {
            get {
                return ResourceManager.GetString("trialExpired_enjoyedHostingFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial has now expired, but you can sign up for an extended trial which includes the rest of Azure as well..
        /// </summary>
        internal static string trialExpired_signupForAzure {
            get {
                return ResourceManager.GetString("trialExpired_signupForAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        internal static string trigger {
            get {
                return ResourceManager.GetString("trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an auth provider.
        /// </summary>
        internal static string tryLanding_chooseAnAuthProvider {
            get {
                return ResourceManager.GetString("tryLanding_chooseAnAuthProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function creation error! Please try again..
        /// </summary>
        internal static string tryLanding_functionError {
            get {
                return ResourceManager.GetString("tryLanding_functionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Function Error.
        /// </summary>
        internal static string tryLanding_functionErrorDetails {
            get {
                return ResourceManager.GetString("tryLanding_functionErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d prefer another supported language, you can choose one later in the functions portal..
        /// </summary>
        internal static string tryLanding_ifYou {
            get {
                return ResourceManager.GetString("tryLanding_ifYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Account.
        /// </summary>
        internal static string tryLanding_microsoftAcccount {
            get {
                return ResourceManager.GetString("tryLanding_microsoftAcccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a free Azure account.
        /// </summary>
        internal static string tryNow_createFreeAzureAccount {
            get {
                return ResourceManager.GetString("tryNow_createFreeAzureAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend trial to 24 hours.
        /// </summary>
        internal static string tryNow_extendTrial {
            get {
                return ResourceManager.GetString("tryNow_extendTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes.
        /// </summary>
        internal static string tryNow_minutes {
            get {
                return ResourceManager.GetString("tryNow_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial expired.
        /// </summary>
        internal static string tryNow_trialExpired {
            get {
                return ResourceManager.GetString("tryNow_trialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial time remaining.
        /// </summary>
        internal static string tryNow_trialTimeRemaining {
            get {
                return ResourceManager.GetString("tryNow_trialTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made here will affect all of the functions within your function app..
        /// </summary>
        internal static string tutorial_changesMade {
            get {
                return ResourceManager.GetString("tutorial_changesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Create a brand-new function&lt;/span&gt; - Get started with one of the prebuilt function templates.
        /// </summary>
        internal static string tutorial_createNew {
            get {
                return ResourceManager.GetString("tutorial_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop.
        /// </summary>
        internal static string tutorial_develop {
            get {
                return ResourceManager.GetString("tutorial_develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Dive into the documentation&lt;/span&gt; - Explore all of the Azure Functions features &lt;a target=&quot;_blank&quot; href=&quot;http://go.microsoft.com/fwlink/?LinkId=747839&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string tutorial_diveIntoDocumentation {
            get {
                return ResourceManager.GetString("tutorial_diveIntoDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function App Settings.
        /// </summary>
        internal static string tutorial_functionAppSettings {
            get {
                return ResourceManager.GetString("tutorial_functionAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate.
        /// </summary>
        internal static string tutorial_integrate {
            get {
                return ResourceManager.GetString("tutorial_integrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrating your functions with other services and data sources is easy..
        /// </summary>
        internal static string tutorial_integrateYourFunction {
            get {
                return ResourceManager.GetString("tutorial_integrateYourFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Steps.
        /// </summary>
        internal static string tutorial_nextSteps {
            get {
                return ResourceManager.GetString("tutorial_nextSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up automated actions based on external triggers, include other input data sources, and send the output to multiple targets..
        /// </summary>
        internal static string tutorial_setUpAutomated {
            get {
                return ResourceManager.GetString("tutorial_setUpAutomated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the tour and start coding.
        /// </summary>
        internal static string tutorial_skip {
            get {
                return ResourceManager.GetString("tutorial_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fastest way to edit code is with the code editor, but you can also use Git.This example uses NodeJS, but many other languages are also supported..
        /// </summary>
        internal static string tutorial_theFastestWay {
            get {
                return ResourceManager.GetString("tutorial_theFastestWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page also includes a log stream and a test console for helping you debug your function..
        /// </summary>
        internal static string tutorial_thisPageInclude {
            get {
                return ResourceManager.GetString("tutorial_thisPageInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Tweak this sample function&lt;/span&gt; - Make it yours on the easy-to-use dashboard.
        /// </summary>
        internal static string tutorial_tweakThisSample {
            get {
                return ResourceManager.GetString("tutorial_tweakThisSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your functions are designed to run within Azure App Service as a function app, and this is where you modify the features of that app..
        /// </summary>
        internal static string tutorial_yourFunction {
            get {
                return ResourceManager.GetString("tutorial_yourFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
    }
}
