//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureFunctions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureFunctions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Functions.
        /// </summary>
        internal static string azureFunctions {
            get {
                return ResourceManager.GetString("azureFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Function Error: {{error}}.
        /// </summary>
        internal static string functionCreateErrorDetails {
            get {
                return ResourceManager.GetString("functionCreateErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function creation error! Please try again..
        /// </summary>
        internal static string functionCreateErrorMessage {
            get {
                return ResourceManager.GetString("functionCreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create + get started.
        /// </summary>
        internal static string gettingStarted_createGetStarted {
            get {
                return ResourceManager.GetString("gettingStarted_createGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Apps.
        /// </summary>
        internal static string gettingStarted_functionApps {
            get {
                return ResourceManager.GetString("gettingStarted_functionApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with Azure Functions.
        /// </summary>
        internal static string gettingStarted_getStarted {
            get {
                return ResourceManager.GetString("gettingStarted_getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New function app.
        /// </summary>
        internal static string gettingStarted_newFunctionApp {
            get {
                return ResourceManager.GetString("gettingStarted_newFunctionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription contains no function apps. These are containers where your functions are executed. Create one now..
        /// </summary>
        internal static string gettingStarted_noFunApps {
            get {
                return ResourceManager.GetString("gettingStarted_noFunApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a function app from &lt;a href=&quot;https://portal.azure.com/#create/Microsoft.FunctionApp&quot;&gt;Azure Portal&lt;/a&gt;..
        /// </summary>
        internal static string gettingStarted_orCreate {
            get {
                return ResourceManager.GetString("gettingStarted_orCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        internal static string gettingStarted_selectLocation {
            get {
                return ResourceManager.GetString("gettingStarted_selectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subscription.
        /// </summary>
        internal static string gettingStarted_selectSubscription {
            get {
                return ResourceManager.GetString("gettingStarted_selectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription {{displayName}} ({{ subscriptionId }}) is not white listed for running functions.
        /// </summary>
        internal static string gettingStarted_subIsNotWhitelisted {
            get {
                return ResourceManager.GetString("gettingStarted_subIsNotWhitelisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subscription contains one or more function apps. These are containers where your functions are executed. Select one or create a new one below..
        /// </summary>
        internal static string gettingStarted_thisSub {
            get {
                return ResourceManager.GetString("gettingStarted_thisSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be at least 2 characters.
        /// </summary>
        internal static string gettingStarted_validateContainer1 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be at most 60 characters.
        /// </summary>
        internal static string gettingStarted_validateContainer2 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain letters, numbers, and hyphens (but the first and last character must be a letter or number).
        /// </summary>
        internal static string gettingStarted_validateContainer3 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function app name {{name}} isn&apos;t available.
        /// </summary>
        internal static string gettingStarted_validateContainer4 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need an Azure subscription in order to use this service. &lt;a href=&quot;https://azure.microsoft.com/en-us/free/&quot;&gt;Click here&lt;/a&gt; to create a free trial subscription.
        /// </summary>
        internal static string gettingStarted_youNeed {
            get {
                return ResourceManager.GetString("gettingStarted_youNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your function apps.
        /// </summary>
        internal static string gettingStarted_yourFunctionApps {
            get {
                return ResourceManager.GetString("gettingStarted_yourFunctionApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription.
        /// </summary>
        internal static string gettingStarted_yourSubscription {
            get {
                return ResourceManager.GetString("gettingStarted_yourSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Choose a language:.
        /// </summary>
        internal static string intro_chooseLanguage {
            get {
                return ResourceManager.GetString("intro_chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Choose a scenario:.
        /// </summary>
        internal static string intro_chooseScenario {
            get {
                return ResourceManager.GetString("intro_chooseScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create this function.
        /// </summary>
        internal static string intro_createThisFunction {
            get {
                return ResourceManager.GetString("intro_createThisFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create your own custom function.
        /// </summary>
        internal static string intro_createYourOwn {
            get {
                return ResourceManager.GetString("intro_createYourOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing.
        /// </summary>
        internal static string intro_dataProcessing {
            get {
                return ResourceManager.GetString("intro_dataProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The faster way to functions.
        /// </summary>
        internal static string intro_fasterWay {
            get {
                return ResourceManager.GetString("intro_fasterWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started quickly with a premade function.
        /// </summary>
        internal static string intro_getStarted {
            get {
                return ResourceManager.GetString("intro_getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or get started on your own.
        /// </summary>
        internal static string intro_getStartedOn {
            get {
                return ResourceManager.GetString("intro_getStartedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d prefer another supported language, choose &quot;Create a function from scratch&quot;..
        /// </summary>
        internal static string intro_ifYou {
            get {
                return ResourceManager.GetString("intro_ifYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start from source control..
        /// </summary>
        internal static string intro_startSC {
            get {
                return ResourceManager.GetString("intro_startSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string intro_timer {
            get {
                return ResourceManager.GetString("intro_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook + API.
        /// </summary>
        internal static string intro_webHook {
            get {
                return ResourceManager.GetString("intro_webHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write any function in minutes - whether to run a simple job that cleans up a database or to build a more complex architecture. Creating functions is easier than ever before, whatever your chosen OS, platform, or development method. No install required..
        /// </summary>
        internal static string intro_writeAny {
            get {
                return ResourceManager.GetString("intro_writeAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made to the current function will be lost. Are you sure you want to continue?.
        /// </summary>
        internal static string topBar_changeMade {
            get {
                return ResourceManager.GetString("topBar_changeMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function app settings.
        /// </summary>
        internal static string topBar_functionAppSettings {
            get {
                return ResourceManager.GetString("topBar_functionAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Azure Functions is available.Visit Function App Settings to upgrade..
        /// </summary>
        internal static string topBar_newVersion {
            get {
                return ResourceManager.GetString("topBar_newVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickstart.
        /// </summary>
        internal static string topBar_quickStart {
            get {
                return ResourceManager.GetString("topBar_quickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string topBar_usage {
            get {
                return ResourceManager.GetString("topBar_usage", resourceCulture);
            }
        }
    }
}
