//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureFunctions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureFunctions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create + get started.
        /// </summary>
        internal static string gettingStarted_createGetStarted {
            get {
                return ResourceManager.GetString("gettingStarted_createGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Apps.
        /// </summary>
        internal static string gettingStarted_functionApps {
            get {
                return ResourceManager.GetString("gettingStarted_functionApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with Azure Functions.
        /// </summary>
        internal static string gettingStarted_getStarted {
            get {
                return ResourceManager.GetString("gettingStarted_getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New function app.
        /// </summary>
        internal static string gettingStarted_newFunctionApp {
            get {
                return ResourceManager.GetString("gettingStarted_newFunctionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription contains no function apps. These are containers where your functions are executed. Create one now..
        /// </summary>
        internal static string gettingStarted_noFunApps {
            get {
                return ResourceManager.GetString("gettingStarted_noFunApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a function app from &lt;a href=&quot;https://portal.azure.com/#create/Microsoft.FunctionApp&quot;&gt;Azure Portal&lt;/a&gt;..
        /// </summary>
        internal static string gettingStarted_orCreate {
            get {
                return ResourceManager.GetString("gettingStarted_orCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        internal static string gettingStarted_selectLocation {
            get {
                return ResourceManager.GetString("gettingStarted_selectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subscription.
        /// </summary>
        internal static string gettingStarted_selectSubscription {
            get {
                return ResourceManager.GetString("gettingStarted_selectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription {{displayName}} ({{ subscriptionId }}) is not white listed for running functions.
        /// </summary>
        internal static string gettingStarted_subIsNotWhitelisted {
            get {
                return ResourceManager.GetString("gettingStarted_subIsNotWhitelisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subscription contains one or more function apps. These are containers where your functions are executed. Select one or create a new one below..
        /// </summary>
        internal static string gettingStarted_thisSub {
            get {
                return ResourceManager.GetString("gettingStarted_thisSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be at least 2 characters.
        /// </summary>
        internal static string gettingStarted_validateContainer1 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be at most 60 characters.
        /// </summary>
        internal static string gettingStarted_validateContainer2 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain letters, numbers, and hyphens (but the first and last character must be a letter or number).
        /// </summary>
        internal static string gettingStarted_validateContainer3 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function app name {{name}} isn&apos;t available.
        /// </summary>
        internal static string gettingStarted_validateContainer4 {
            get {
                return ResourceManager.GetString("gettingStarted_validateContainer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need an Azure subscription in order to use this service. &lt;a href=&quot;https://azure.microsoft.com/en-us/free/&quot;&gt;Click here&lt;/a&gt; to create a free trial subscription.
        /// </summary>
        internal static string gettingStarted_youNeed {
            get {
                return ResourceManager.GetString("gettingStarted_youNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your function apps.
        /// </summary>
        internal static string gettingStarted_yourFunctionApps {
            get {
                return ResourceManager.GetString("gettingStarted_yourFunctionApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription.
        /// </summary>
        internal static string gettingStarted_yourSubscription {
            get {
                return ResourceManager.GetString("gettingStarted_yourSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
    }
}
