//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureFunctions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureFunctions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with Azure Functions.
        /// </summary>
        internal static string gettingStarted0 {
            get {
                return ResourceManager.GetString("gettingStarted0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need an Azure subscription in order to use this service. &lt;a href=&quot;https://azure.microsoft.com/en-us/free/&quot;&gt;Click here&lt;/a&gt; to create a free trial subscription.
        /// </summary>
        internal static string gettingStarted1 {
            get {
                return ResourceManager.GetString("gettingStarted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        internal static string gettingStarted10 {
            get {
                return ResourceManager.GetString("gettingStarted10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a function app from &lt;a href=&quot;https://portal.azure.com/#create/Microsoft.FunctionApp&quot;&gt;Azure Portal&lt;/a&gt;..
        /// </summary>
        internal static string gettingStarted11 {
            get {
                return ResourceManager.GetString("gettingStarted11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string gettingStarted12 {
            get {
                return ResourceManager.GetString("gettingStarted12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create + get started.
        /// </summary>
        internal static string gettingStarted13 {
            get {
                return ResourceManager.GetString("gettingStarted13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string gettingStarted14 {
            get {
                return ResourceManager.GetString("gettingStarted14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string gettingStarted15 {
            get {
                return ResourceManager.GetString("gettingStarted15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription.
        /// </summary>
        internal static string gettingStarted2 {
            get {
                return ResourceManager.GetString("gettingStarted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string gettingStarted3 {
            get {
                return ResourceManager.GetString("gettingStarted3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subscription.
        /// </summary>
        internal static string gettingStarted4 {
            get {
                return ResourceManager.GetString("gettingStarted4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your function apps.
        /// </summary>
        internal static string gettingStarted5 {
            get {
                return ResourceManager.GetString("gettingStarted5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subscription contains one or more function apps. These are containers where your functions are executed. Select one or create a new one below..
        /// </summary>
        internal static string gettingStarted6 {
            get {
                return ResourceManager.GetString("gettingStarted6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function apps.
        /// </summary>
        internal static string gettingStarted7 {
            get {
                return ResourceManager.GetString("gettingStarted7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New function app.
        /// </summary>
        internal static string gettingStarted8 {
            get {
                return ResourceManager.GetString("gettingStarted8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription contains no function apps. These are containers where your functions are executed. Create one now..
        /// </summary>
        internal static string gettingStarted9 {
            get {
                return ResourceManager.GetString("gettingStarted9", resourceCulture);
            }
        }
    }
}
