export const ADD_PERMISSION = 'ADD_PERMISSION';
export const REMOVE_PERMISSION = 'REMOVE_PERMISSION';
export const ADD_READONLY_LOCK = 'ADD_READONLY_LOCK';
export const REMOVE_READONLY_LOCK = 'REMOVE_READONLY_LOCK';
export const ADD_READONLY_LOCK_CALLED = 'ADD_READONLY_LOCK_CALLED';
export const REMOVE_READONLY_LOCK_CALLED = 'REMOVE_READONLY_LOCK_CALLED';
export const ADD_PERMISSION_CALLED = 'ADD_PERMISSION_CALLED';
export const REMOVE_PERMISSIONS_CALLED = 'REMOVE_PERMISSIONS_CALLED';
