import { ITheme } from 'office-ui-fabric-react/lib-commonjs/Styling';

const lightTheme: ITheme = {
  palette: {
    themeDarker: '#004578',
    themeDark: '#005a9e',
    themeDarkAlt: '#106ebe',
    themePrimary: '#0078d4',
    themeSecondary: '#2b88d8',
    themeTertiary: '#71afe5',
    themeLight: '#c7e0f4',
    themeLighter: '#deecf9',
    themeLighterAlt: '#eff6fc',
    black: '#000000',
    blackTranslucent40: 'rgba(0,0,0,.4)',
    neutralDark: '#212121',
    neutralPrimary: '#333333',
    neutralPrimaryAlt: '#3c3c3c',
    neutralSecondary: '#666666',
    neutralSecondaryAlt: '#767676',
    neutralTertiary: '#a6a6a6',
    neutralTertiaryAlt: '#c8c8c8',
    neutralQuaternary: '#d0d0d0',
    neutralQuaternaryAlt: '#dadada',
    neutralLight: '#eaeaea',
    neutralLighter: '#f4f4f4',
    neutralLighterAlt: '#f8f8f8',
    accent: '#0078d4',
    white: '#ffffff',
    whiteTranslucent40: 'rgba(255,255,255,.4)',
    yellow: '#ffb900',
    yellowLight: '#fff100',
    orange: '#d83b01',
    orangeLight: '#ea4300',
    orangeLighter: '#ff8c00',
    redDark: '#a80000',
    red: '#e81123',
    magentaDark: '#5c005c',
    magenta: '#b4009e',
    magentaLight: '#e3008c',
    purpleDark: '#32145a',
    purple: '#5c2d91',
    purpleLight: '#b4a0ff',
    blueDark: '#002050',
    blueMid: '#00188f',
    blue: '#0078d4',
    blueLight: '#00bcf2',
    tealDark: '#004b50',
    teal: '#008272',
    tealLight: '#00b294',
    greenDark: '#004b1c',
    green: '#107c10',
    greenLight: '#bad80a',
  },
  fonts: {
    tiny: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '10px',
      fontWeight: 600,
    },
    xSmall: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '11px',
      fontWeight: 400,
    },
    small: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '12px',
      fontWeight: 400,
    },
    smallPlus: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '13px',
      fontWeight: 400,
    },
    medium: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '14px',
      fontWeight: 400,
    },
    mediumPlus: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '15px',
      fontWeight: 400,
    },
    large: {
      fontFamily: "'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '17px',
      fontWeight: 300,
    },
    xLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '21px',
      fontWeight: 100,
    },
    xxLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '28px',
      fontWeight: 100,
    },
    superLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '42px',
      fontWeight: 100,
    },
    mega: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '72px',
      fontWeight: 100,
    },
  },
  semanticColors: {
    bodyBackground: '#ffffff',
    bodyStandoutBackground: '#ffffff',
    bodyFrameBackground: '#ffffff',
    bodyFrameDivider: '#eaeaea',
    bodyText: '#333333',
    bodyTextChecked: '#000000',
    bodySubtext: '#666666',
    bodyDivider: '#c8c8c8',
    disabledBackground: '#f4f4f4',
    disabledText: '#a6a6a6',
    disabledBodyText: '#c8c8c8',
    disabledSubtext: '#d0d0d0',
    focusBorder: '#000000',
    variantBorder: '#eaeaea',
    variantBorderHovered: '#a6a6a6',
    defaultStateBackground: '#eaeaea',
    errorText: '#a80000',
    warningText: '#333333',
    errorBackground: 'rgba(232, 17, 35, .2)',
    blockingBackground: 'rgba(234, 67, 0, .2)',
    warningBackground: 'rgba(255, 185, 0, .2)',
    warningHighlight: '#ffb900',
    successBackground: 'rgba(186, 216, 10, .2)',
    inputBorder: '#a6a6a6',
    inputBorderHovered: '#212121',
    inputBackground: '#ffffff',
    inputBackgroundChecked: '#0078d4',
    inputBackgroundCheckedHovered: '#106ebe',
    inputForegroundChecked: '#ffffff',
    inputFocusBorderAlt: '#0078d4',
    smallInputBorder: '#666666',
    inputPlaceholderText: '#666666',
    buttonBackground: '#f4f4f4',
    buttonBackgroundChecked: '#c8c8c8',
    buttonBackgroundHovered: '#eaeaea',
    buttonBackgroundCheckedHovered: '#eaeaea',
    buttonBackgroundPressed: '#eaeaea',
    buttonBorder: 'transparent',
    buttonText: '#333333',
    buttonTextHovered: '#000000',
    buttonTextChecked: '#212121',
    buttonTextCheckedHovered: '#000000',
    buttonTextPressed: '#212121',
    buttonTextDisabled: '#d0d0d0',
    buttonBorderDisabled: 'transparent',
    primaryButtonBackground: '#0078d4',
    primaryButtonBackgroundHovered: '#106ebe',
    primaryButtonBackgroundPressed: '#005a9e',
    primaryButtonBorder: 'transparent',
    primaryButtonText: '#ffffff',
    primaryButtonTextHovered: '#ffffff',
    primaryButtonTextPressed: '#ffffff',
    menuItemBackgroundHovered: '#f4f4f4',
    menuIcon: '#0078d4',
    menuHeader: '#0078d4',
    listBackground: '#ffffff',
    listText: '#333333',
    listItemBackgroundHovered: '#f4f4f4',
    listItemBackgroundChecked: '#eaeaea',
    listItemBackgroundCheckedHovered: '#dadada',
    listHeaderBackgroundHovered: '#f4f4f4',
    listHeaderBackgroundPressed: '#eaeaea',
    actionLink: '#333333',
    actionLinkHovered: '#212121',
    link: '#0078d4',
    linkHovered: '#004578',
    listTextColor: '#333333',
    menuItemBackgroundChecked: '#eaeaea',
  },
  isInverted: false,
  disableGlobalClassNames: false,
  typography: {
    families: {
      default:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      monospace: 'Menlo, Monaco, "Courier New", monospace',
    },
    sizes: {
      mini: '10px',
      xSmall: '11px',
      small: '12px',
      smallPlus: '13px',
      medium: '14px',
      mediumPlus: '15px',
      large: '17px',
      xLarge: '21px',
      xxLarge: '28px',
      mega: '72px',
    },
    weights: { default: 400, regular: 400, light: 100, semibold: 600, bold: 700 },
    variants: {
      default: {
        family:
          "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
        size: '14px',
        weight: 400,
      },
      caption: {
        family:
          "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
        size: '11px',
        weight: 400,
      },
      h1: {
        family:
          "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
        size: '72px',
        weight: 100,
      },
      h2: {
        family:
          "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
        size: '28px',
        weight: 100,
      },
      h3: {
        family:
          "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
        size: '21px',
        weight: 100,
      },
      h4: {
        family:
          "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
        size: '17px',
        weight: 100,
      },
      h5: {
        family:
          "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
        size: '15px',
        weight: 100,
      },
      link: {
        family:
          "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
        size: '14px',
        weight: 400,
        color: 'link',
        hoverColor: 'linkHovered',
      },
    },
  },
};

export default lightTheme;
