# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - ${webAppName}

on:
  push:
    branches:
      - ${branch}
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '${runtimeStackVersion}'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${siteName}'
          slot-name: '${slot}'
          publish-profile: \${{ secrets.${secretName} }}
          package: '\${{ github.workspace }}/target/*.jar'
