name: "Auto-merge Validation"

on:
  pull_request:
    paths:
      - 'server/Resources/**/Resources.resx.lcl'
env:
    AUTO_LOCALIZATION_LABEL: 'auto-localization-update'
    
jobs:
  auto-merge-lcl-changes:
    if: ${{ github.actor == 'takyyon' }}
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Auto-Label
      uses: andymckay/labeler@master
      with:
        add-labels: "${{ env.AUTO_LOCALIZATION_LABEL }}"
        ignore-if-assigned: true
        
    - name: Auto-approve
      run: gh pr review --approve "$PR_URL"
        
    - name: Enable Auto-merge
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
